name: Workflow Test

on:
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list and read files
        run: |
             echo "action test"
             ls -ltra
             cat README.md

      - name: generate some ascii
        run: cowsay -f dragon "boooo" >> sickart.txt

    #   - name: List Files
    #     run: ls

    #   - name: Read File
    #     run: cat README.md

