name: Workflow Test

on:
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: First Action
        run: echo "action test"

      - name: List Files
        run: ls

      - name: Read File
        run: cat README.md